//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CornerSites.Web.Modules {
    
    
    public partial class AddsSubscription {
        
        /// <summary>
        /// tbcSubscription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabContainer tbcSubscription;
        
        /// <summary>
        /// tpIndividuals control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel tpIndividuals;
        
        /// <summary>
        /// cntIndividuals control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.Modules.SubscriptionIndividuals cntIndividuals;
        
        /// <summary>
        /// cntServicePack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.Modules.SubscriptionServicePack cntServicePack;
        
        /// <summary>
        /// tbAgents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel tbAgents;
        
        /// <summary>
        /// cntAgents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.Modules.SubscriptionAgents cntAgents;
        
        /// <summary>
        /// cntAgentServicePack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.Modules.SubscriptionServicePack cntAgentServicePack;
        
        /// <summary>
        /// tbBuilders control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel tbBuilders;
        
        /// <summary>
        /// cntBuilders control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.Modules.SubscriptionBuilders cntBuilders;
        
        /// <summary>
        /// cntBuildersServicepack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.Modules.SubscriptionServicePack cntBuildersServicepack;
        
        /// <summary>
        /// rptSubscription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptSubscription;
    }
}
