//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CornerSites.Web {
    
    
    public partial class MyAccount {
        
        /// <summary>
        /// cntProfileInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.Modules.MyAccount.ProfileInfo cntProfileInfo;
        
        /// <summary>
        /// cntMySuscription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.Modules.MyAccount.MySubscription cntMySuscription;
        
        /// <summary>
        /// cntMyAds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.Modules.MyAccount.MyAds cntMyAds;
    }
}
