//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CornerSites.Web.AdsAdmin.Modules {
    
    
    public partial class StudioApartment {
        
        /// <summary>
        /// cntPropertyFeatures control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.AdsAdmin.Modules.PropertyFeatures cntPropertyFeatures;
        
        /// <summary>
        /// cntPropertyTermsAndConditions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.AdsAdmin.Modules.PropertyTermsAndConditions cntPropertyTermsAndConditions;
        
        /// <summary>
        /// cntAmenities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.AdsAdmin.Modules.Amenities cntAmenities;
        
        /// <summary>
        /// cntDistanceFromKeyLocations control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CornerSites.Web.AdsAdmin.Modules.DistanceFromKeyLocations cntDistanceFromKeyLocations;
    }
}
